// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: emp.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmpServiceClient is the client API for EmpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmpServiceClient interface {
	EmitEmp(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type empServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmpServiceClient(cc grpc.ClientConnInterface) EmpServiceClient {
	return &empServiceClient{cc}
}

func (c *empServiceClient) EmitEmp(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/emp.EmpService/EmitEmp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmpServiceServer is the server API for EmpService service.
// All implementations must embed UnimplementedEmpServiceServer
// for forward compatibility
type EmpServiceServer interface {
	EmitEmp(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedEmpServiceServer()
}

// UnimplementedEmpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmpServiceServer struct {
}

func (UnimplementedEmpServiceServer) EmitEmp(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitEmp not implemented")
}
func (UnimplementedEmpServiceServer) mustEmbedUnimplementedEmpServiceServer() {}

// UnsafeEmpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmpServiceServer will
// result in compilation errors.
type UnsafeEmpServiceServer interface {
	mustEmbedUnimplementedEmpServiceServer()
}

func RegisterEmpServiceServer(s grpc.ServiceRegistrar, srv EmpServiceServer) {
	s.RegisterService(&EmpService_ServiceDesc, srv)
}

func _EmpService_EmitEmp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmpServiceServer).EmitEmp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emp.EmpService/EmitEmp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmpServiceServer).EmitEmp(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// EmpService_ServiceDesc is the grpc.ServiceDesc for EmpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emp.EmpService",
	HandlerType: (*EmpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitEmp",
			Handler:    _EmpService_EmitEmp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emp.proto",
}
